name: Packer Build

on:
  push:
    paths:
      - 'infra/packer/*'

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup packer
          uses: hashicorp/setup-packer@main

        - name: Set up environment variables
          run: |
            ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY  }}
            echo "ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY  }}" >> $GITHUB_ENV
            SECRET_KEY=${{ secrets.AWS_SECRET_KEY  }}
            echo "SECRET_KEY=${{ secrets.AWS_SECRET_KEY  }}" >> $GITHUB_ENV


        - name: Run `packer init`

          run: "packer init ./infra/packer/aws-ubuntu.pkr.hcl"

        - name: Run `packer validate`
          run: "packer validate --var ACCESS_KEY=$ACCESS_KEY ./infra/packer/aws-ubuntu.pkr.hcl"

        - name: Run `packer build`
          run: "packer build ./infra/packer/aws-ubuntu.pkr.hcl"
